name       : picard
version    : 2.5.2
release    : 20
source     :
    - https://github.com/metabrainz/picard/archive/release-2.5.2.tar.gz : 925e197b99ae64f5515c893f69fa095fd11b84d0958a93f68bc87a665a9a0811
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python-dateutil
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python-dateutil
    - python3-qt5
    - python-discid
setup      : |
    %patch -p1 < $pkgfiles/Use-system-theme.patch
install    : |
    %python3_install --disable-autoupdate
check      : |
    %python3_test
