name       : picard
version    : 2.4.4
release    : 18
source     :
    - https://github.com/metabrainz/picard/archive/release-2.4.4.tar.gz : 3e6a1abb886c859a20c164bec76e65a90b6b8d5a0c303a39d1432a39483cb4b0
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python-dateutil
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python-dateutil
    - python3-qt5
    - python-discid
setup      : |
    %patch -p1 < $pkgfiles/Use-system-theme.patch
install    : |
    %python3_install --disable-autoupdate
check      : |
    %python3_test
