name       : picard
version    : 2.0.3
release    : 7
source     :
    - https://github.com/metabrainz/picard/archive/release-2.0.3.tar.gz : bc56dbd744d736e2b75645c3d37a1a383e7e1b591d2a09ee988be67fff1deea6
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups
    and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python3-qt5
    - python3-sip
rundeps    :
    - chromaprint
    - mutagen
    - python3-qt5
build      : |
    %python3_setup build_ext -i
    %python3_setup build_locales -i
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
