name       : picard
version    : 2.8.5
release    : 29
source     :
    - https://github.com/metabrainz/picard/archive/refs/tags/release-2.8.5.tar.gz : b1c1f76d5fe92cb481f4362142c6a84f1cf45948e42cfd7c3d3beffd703c54ce
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python-dateutil
    - python-fasteners
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python-dateutil
    - python-discid
    - python-fasteners
    - python3-qt5
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/Use-system-theme.patch
install    : |
    %python3_install --disable-autoupdate
check      : |
    %python3_test
