name       : picard
version    : 1.3.2
release    : 3
source     :
    - http://ftp.musicbrainz.org/pub/musicbrainz/picard/picard-1.3.2.tar.gz : e728234560b82eb33d3143a53d3bbb92833455fd130f8d2083193cffceea4120
license    : GPL-2.0
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python
rundeps    :
    - chromaprint
    - mutagen
    - python-qt4
build      : |
    python setup.py build_ext -i
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
    cp -r contrib/plugins/* $installdir/usr/lib/python2.7/site-packages/picard/plugins/
