name       : picard
version    : 2.3.1
release    : 15
source     :
    - https://github.com/metabrainz/picard/archive/release-2.3.1.tar.gz : 7466678a82f29d1376ab07370750d096fcc1305b8d8fe52f7729e3f7841b8e33
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python3-qt5
    - python-discid
install    : |
    %python3_install --disable-autoupdate
check      : |
    %python3_test
