name       : picard
version    : 2.6.1
release    : 23
source     :
    - https://github.com/metabrainz/picard/archive/refs/tags/release-2.6.1.tar.gz : 5b51a4d7a669b25fe61889c1273c020f921d3cedb18049c8071171ac54746545
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python-dateutil
    - python-fasteners
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python-dateutil
    - python-discid
    - python-fasteners
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/Use-system-theme.patch
install    : |
    %python3_install --disable-autoupdate
check      : |
    %python3_test
