name       : picard
version    : 1.4.2
release    : 4
source     :
    - https://github.com/metabrainz/picard/archive/release-1.4.2.tar.gz : f0adee3877bbd66c827a43b57dd2233037b99f6ebfdc1700b26cb9d400992234
license    : GPL-2.0
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups
    and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - python-sip
rundeps    :
    - chromaprint
    - mutagen
    - python-qt4
build      : |
    %python_setup build_ext -i
    %python_setup build_locales -i
install    : |
    %python_install
