name       : picard
version    : 2.6.4
release    : 24
source     :
    - https://github.com/metabrainz/picard/archive/refs/tags/release-2.6.4.tar.gz : c71ec4605842e24bbe6d92639e1cafac943548afed3a05193488d4bcc3d95370
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python-dateutil
    - python-fasteners
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python-dateutil
    - python-discid
    - python-fasteners
    - python3-qt5
setup      : |
    %patch -p1 < $pkgfiles/Use-system-theme.patch
install    : |
    %python3_install --disable-autoupdate
check      : |
    %python3_test
