name       : picard
version    : 2.1.3
release    : 10
source     :
    - https://github.com/metabrainz/picard/archive/release-2.1.3.tar.gz : 8e044fe68c44d345c19f98952c3c7f20c72da74dbac9ce7c7b0621e2d69885a7
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python3-qt5
    - python-discid
build      : |
    %python3_setup build_ext -i
    %python3_setup build_locales -i
install    : |
    %python3_install
check      : |
    %python3_test
