name       : picard
version    : 2.2.3
release    : 12
source     :
    - https://github.com/metabrainz/picard/archive/release-2.2.3.tar.gz : 920bc0ffc1b5ae395456698a133799aee06c66b4446f6a388a64046e07d8716b
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-platform music tagger written in Python
description: |
    Cross-platform music tagger written in Python.
    Picard supports the majority of audio file formats, is capable of using audio fingerprints (AcoustIDs), performing CD lookups and disc ID submissions, and it has excellent Unicode support.
    Additionally, there are several plugins available that extend Picard's features.
builddeps  :
    - pkgconfig(python3)
    - mutagen
    - python3-qt5
rundeps    :
    - chromaprint
    - mutagen
    - python3-qt5
    - python-discid
build      : |
    %python3_setup --disable-autoupdate
install    : |
    %python3_install
check      : |
    %python3_test
